name = "ghoti-worker"
main = "worker.js"
compatibility_date = "2026-09-17"
workers_dev = true

# GHOTI MARKET landing product URLs
[[routes]]
pattern = "ghotimarket.com/landing/product*"
zone_name = "ghotimarket.com"

[[routes]]
pattern = "www.ghotimarket.com/landing/product*"
zone_name = "ghotimarket.com"
