name = "ghoti-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# আপনার ৪ টা লিংকই কভার করবে
[[routes]]
pattern = "ghotimarket.com/landing/product*"
zone_name = "ghotimarket.com"

[[routes]]
pattern = "www.ghotimarket.com/landing/product*"
zone_name = "ghotimarket.com"
